Repository CeladonSS13/Foundation-19, pull requests merged in 2024-05, with the labels that each got.

#54 Update README.md
  mod_celadon/README.md
Labels: 🔎 Требует рассмотрения 🔍, 📃 Документация 📃

#62 More LCZ Fixes
  mod_celadon/__maps/maps/site53/site53-1.dmm
Labels: 🗺 Карты 🗺

#58 Notebook
  code/modules/SCP/SCPs/SCP-096.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
  code/modules/modular_computers/computers/subtypes/dev_laptop.dm
  mod_celadon/SCP096/README.md
  mod_celadon/SCP096/code/SCP096.dm
  mod_celadon/SCP096/code/keybinds.dm
  mod_celadon/laptop_rotate/icons/laptop_rotate.dmi
  mod_celadon/laptop_rotate/icons/laptop_rotate_1.dmi
Labels: 🥇 Молодец! 🥇, ⁉ Вопросы ⁉, 🛠 Доработать 🛠, 🧱 Код 🧱, Code

#74 Перенос обновлений с beta-dev на stable #3
  .github/workflows/labeler.yml
  .github/workflows/release.yml
  mod_celadon/__maps/maps/site53/site53-1.dmm
  mod_celadon/__maps/maps/site53/site53-2.dmm
  mod_celadon/__maps/maps/site53/site53-5.dmm
  tgui/package.json
  tgui/packages/tgui-bench/package.json
  tgui/packages/tgui-dev-server/package.json
  tgui/packages/tgui-polyfill/package.json
  tgui/yarn.lock
  tools/autowiki/package-lock.json
  tools/autowiki/package.json
  tools/requirements.txt
Labels: TGUI, Github, Tools

#77 A little SCp 106 Fixes
  mod_celadon/__maps/maps/site53/site53-1.dmm
  mod_celadon/__maps/maps/site53/site53-5.dmm
Labels: 🗺 Карты 🗺

#79 Hotfix
  mod_celadon/sci_job_names/README..md
  mod_celadon/sci_job_names/_sci_job_names.dm
  mod_celadon/sci_job_names/code/job/research.dm
Labels: 🧱 Код 🧱

#81 Update README.md
  mod_celadon/README.md
Labels: 🧱 Код 🧱, Фикс

#80 Update README.md
  mod_celadon/_example/README.md
Labels: 🧱 Код 🧱, Фикс

#82 NEW Admin Zone
  mod_celadon/__maps/maps/site53/z1_admin.dmm
Labels: 🗺 Карты 🗺

#86 Add automatic UTF-8 insertion
  baystation12.dme
  code/__defines/~mods/_master_defines.dm
  mod_celadon/mod_celadon.dme
  mod_celadon/utf_8/README.md
  mod_celadon/utf_8/_utf_8.dm
  mod_celadon/utf_8/_utf_8.dme
  mod_celadon/utf_8/code/utf_8.dm
Labels: 🧱 Код 🧱

#84 LCZ cameranet fixes
  mod_celadon/__maps/maps/site53/site53-1.dmm
  mod_celadon/__maps/maps/site53/site53-3.dmm
Labels: 🗺 Карты 🗺

#85 contraband_fix
  mod_celadon/contraband_fix/README.md
  mod_celadon/contraband_fix/_contraband_fix.dm
  mod_celadon/contraband_fix/_contraband_fix.dme
  mod_celadon/contraband_fix/code/contraband_fix.dm
  mod_celadon/mod_celadon.dme
Labels: 🧱 Код 🧱
